name: "mc_retronet_hu"

services:
  db:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=${DB_ENGINE_DATABASE}"
      - "MYSQL_PASSWORD=${DB_ENGINE_PASSWORD}"
      - "MYSQL_USER=${DB_ENGINE_USERNAME}"
      - "MYSQL_ROOT_PASSWORD=${DB_ENGINE_ROOT_PASSWORD}"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ".run/db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 0s

  worker:
    image: cr.czompicloud.hu/retronetmc/yggdrasil-server:latest
    build:
      context: .
    volumes:
      - ".run/worker/data:/data"
      - ".run/worker/logs:/logs"
    environment:
      - DB_ENGINE_PROVIDER
      - DB_ENGINE_HOSTPORT
      - DB_ENGINE_USERNAME
      - DB_ENGINE_PASSWORD
      - DB_ENGINE_DATABASE
      - AUTH_SERVER_JWT_SECRET
      - AUTH_SERVER_KEY_SEED
      - MSA_CLIENT_ID
      - MSA_CLIENT_SECRET
      - MSA_KEYSTORE_NAME
      - MSA_KEYSTORE_PATH
      - MSA_KEYSTORE_PASS
      - BASE_URL
      - APP_LOG_LEVEL
      - ENVIRONMENT
      - TLS_KEYSTORE_NAME
      - TLS_KEYSTORE_PATH
      - TLS_KEYSTORE_PASS
      - TLS_CERTIFICATE_PATH
      - TLS_PRIVATE_KEY_PATH
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    driver: bridge
    name: mc_retronet_hu
