
# Server HTTPS port
server.port=5001

# Enable SSL for HTTPS
server.ssl.enabled=true

# SSL configuration
server.ssl.key-store=/data/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=default-certificate

debug=false

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.thymeleaf.cache=false

server.servlet.session.timeout=7d
server.servlet.session.cookie.max-age=7d
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=lax

logging.file.name=/logs/yggdrasil-platform.log
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-file-size=100MB
logging.logback.rollingpolicy.max-history=30

logging.level.hu.retronet.mc=${APP_LOG_LEVEL:INFO}
logging.level.com.czompi.mcservicessdk=${APP_LOG_LEVEL:INFO}
