
# Server HTTPS port
server.port=5001

# Enable SSL for HTTPS
server.ssl.enabled=true

# SSL configuration
server.ssl.key-store=/data/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=default-certificate

debug=false
